#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Copyright 2025 Enactic, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import argparse
import time
from enum import IntEnum

import numpy as np
import damiao_can as oa


class JointID(IntEnum):
    J1 = 0
    J2 = 1
    J3 = 2
    J4 = 3
    J5 = 4
    J6 = 5
    J7 = 6


MECH_LIM_V1 = {
    JointID.J1: [np.deg2rad(-80), np.deg2rad(200)],
    JointID.J2: [np.deg2rad(-100), np.deg2rad(100)],
    JointID.J3: [np.deg2rad(-90), np.deg2rad(90)],
    JointID.J4: [np.deg2rad(0), np.deg2rad(140)],
    JointID.J5: [np.deg2rad(-90), np.deg2rad(90)],
    JointID.J6: [np.deg2rad(-45), np.deg2rad(45)],
    JointID.J7: [np.deg2rad(-90), np.deg2rad(90)],
}

MECH_LIM_V2_RIGHT = dict(MECH_LIM_V1)
MECH_LIM_V2_LEFT = dict(MECH_LIM_V1)

JOINT_SIGN = {
    JointID.J1: -1.0,
    JointID.J2: -1.0,
    JointID.J3: +1.0,
    JointID.J4: +1.0,
    JointID.J5: +1.0,
    JointID.J6: +1.0,
    JointID.J7: +1.0,
}


def interpolate(device, joint_id: JointID, delta_rad,
                kp=52.0, kd=1.5, torque_assist=0.0, interp_time=2.0):
    """Linearly move one motor from its current position by delta_rad."""
    idx = int(joint_id)
    q0 = device.get_motors()[idx].get_position()
    q1 = q0 + float(delta_rad)
    n_steps = 500
    dt = interp_time / n_steps
    tau = np.copysign(1.0, q1 - q0) * abs(torque_assist)

    for i in range(n_steps + 1):
        alpha = i / n_steps
        q = q0 + (q1 - q0) * alpha
        device.mit_control_one(idx, oa.MITParam(kp, kd, q, 0.0, tau))
        device.recv_all()
        time.sleep(dt)


def _hit_thresholds(idx):
    if idx == 0:
        return 0.0125, 5.0
    return 0.1, 2.0


def bump_to_limit(device, joint_id, step_deg=0.2, kp=45.0, kd=1.2,
                  torque_bias=0.0):
    """Step one motor until its mechanical stop and return traveled delta [rad]."""
    idx = int(joint_id)
    step_rad = np.deg2rad(step_deg)
    tau_cmd = np.copysign(1.0, step_deg) * abs(torque_bias)
    q_start = device.get_motors()[idx].get_position()
    q_target = q_start
    dq_th, tau_th = _hit_thresholds(idx)

    while True:
        q_target += step_rad
        device.mit_control_one(idx, oa.MITParam(
            kp, kd, q_target, 0.0, tau_cmd))
        device.recv_all()
        time.sleep(0.005)

        motor = device.get_motors()[idx]
        if abs(motor.get_velocity()) < dq_th and abs(motor.get_torque()) > tau_th:
            delta_rad = motor.get_position() - q_start
            print(
                f"[INFO] mechanical stop ({joint_id.name}): "
                f"{delta_rad:.4f} rad / {np.rad2deg(delta_rad):.2f}°"
            )
            return float(delta_rad)


def calc_delta_to_zero_pos_joint(initial_rad, ideal_limit_rad,
                                 delta_to_stop_rad, joint_id):
    q_hit = initial_rad + delta_to_stop_rad
    return float(JOINT_SIGN.get(joint_id, 1.0) * (ideal_limit_rad - q_hit))


def _run_right_sequence(device, mech_lim):
    d_j4 = bump_to_limit(device, JointID.J4, step_deg=-0.2)
    time.sleep(0.5)

    interpolate(device, JointID.J2, np.deg2rad(5), interp_time=0.4)
    time.sleep(0.5)
    d_j3 = bump_to_limit(device, JointID.J3)
    time.sleep(0.5)

    interpolate(device, JointID.J3, -mech_lim[JointID.J3][1], interp_time=1.0)
    time.sleep(0.5)
    interpolate(device, JointID.J2, -np.deg2rad(5), interp_time=0.4)
    time.sleep(0.5)
    interpolate(device, JointID.J4, np.pi / 2.0)
    time.sleep(0.5)

    d_j5 = bump_to_limit(device, JointID.J5)
    time.sleep(0.5)
    interpolate(device, JointID.J5, -mech_lim[JointID.J5][1])
    time.sleep(0.5)

    d_j6 = bump_to_limit(device, JointID.J6)
    time.sleep(0.5)
    interpolate(device, JointID.J6, -mech_lim[JointID.J6][1])
    time.sleep(0.5)

    d_j7 = bump_to_limit(device, JointID.J7)
    time.sleep(0.5)
    interpolate(device, JointID.J7, -mech_lim[JointID.J7][1])
    time.sleep(0.5)

    d_j2 = bump_to_limit(device, JointID.J2, step_deg=-0.2)
    time.sleep(0.5)
    interpolate(device, JointID.J2, np.deg2rad(
        10), interp_time=0.9, kp=280, kd=2.0)
    time.sleep(0.5)

    d_j1 = bump_to_limit(device, JointID.J1, step_deg=-0.2, kp=280, kd=2.1)
    time.sleep(0.5)
    interpolate(device, JointID.J1, np.deg2rad(80))
    time.sleep(0.5)

    interpolate(device, JointID.J4, -np.pi / 2.0)
    time.sleep(2.5)

    ideal = {
        JointID.J7: np.pi / 2.0,
        JointID.J6: np.pi / 4.0,
        JointID.J5: np.pi / 2.0,
        JointID.J4: 0.0,
        JointID.J3: np.pi / 2.0,
        JointID.J2: np.deg2rad(-10),
        JointID.J1: np.deg2rad(-80),
    }
    return ideal, [d_j1, d_j2, d_j3, d_j4, d_j5, d_j6, d_j7]


def _run_left_sequence(device, mech_lim):
    d_j4 = bump_to_limit(device, JointID.J4, step_deg=-0.2)
    time.sleep(0.5)

    interpolate(device, JointID.J2, -np.deg2rad(5), interp_time=0.4)
    time.sleep(0.5)
    d_j3 = bump_to_limit(device, JointID.J3)
    time.sleep(0.5)

    interpolate(device, JointID.J3, -mech_lim[JointID.J3][1], interp_time=1.0)
    time.sleep(0.5)
    interpolate(device, JointID.J2, np.deg2rad(5), interp_time=0.4)
    time.sleep(0.5)
    interpolate(device, JointID.J4, np.pi / 2.0)
    time.sleep(0.5)

    d_j5 = bump_to_limit(device, JointID.J5)
    time.sleep(0.5)
    interpolate(device, JointID.J5, -mech_lim[JointID.J5][1])
    time.sleep(0.5)

    d_j6 = bump_to_limit(device, JointID.J6)
    time.sleep(0.5)
    interpolate(device, JointID.J6, -mech_lim[JointID.J6][1])
    time.sleep(0.5)

    d_j7 = bump_to_limit(device, JointID.J7)
    time.sleep(0.5)
    interpolate(device, JointID.J7, -mech_lim[JointID.J7][1])
    time.sleep(0.5)

    d_j2 = bump_to_limit(device, JointID.J2)
    time.sleep(0.5)
    interpolate(device, JointID.J2, -np.deg2rad(10),
                interp_time=0.9, kp=280, kd=2.0)
    time.sleep(0.5)

    d_j1 = bump_to_limit(device, JointID.J1, kp=280, kd=2.1)
    time.sleep(0.5)
    interpolate(device, JointID.J1, -np.deg2rad(80))
    time.sleep(0.5)

    interpolate(device, JointID.J4, -np.pi / 2.0)
    time.sleep(2.5)

    ideal = {
        JointID.J7: np.pi / 2.0,
        JointID.J6: np.pi / 4.0,
        JointID.J5: np.pi / 2.0,
        JointID.J4: 0.0,
        JointID.J3: np.pi / 2.0,
        JointID.J2: np.deg2rad(10),
        JointID.J1: np.deg2rad(80),
    }
    return ideal, [d_j1, d_j2, d_j3, d_j4, d_j5, d_j6, d_j7]


def main():
    parser = argparse.ArgumentParser(description="Zero-position calibration")
    parser.add_argument("--canport", type=str, default=None)
    parser.add_argument(
        "--side", type=str, default="right", choices=["right", "left"]
    )
    parser.add_argument("--robot-version", type=str,
                        default="v2", choices=["v1", "v2"])
    args = parser.parse_args()

    if args.canport is None:
        args.canport = "can1" if args.side == "left" else "can0"

    if args.robot_version == "v2":
        mech_lim = MECH_LIM_V2_RIGHT if args.side == "right" else MECH_LIM_V2_LEFT
    else:
        mech_lim = MECH_LIM_V1

    device = oa.DamiaoCAN(args.canport, True)
    device.init_motors(
        [
            oa.MotorType.DM8009,
            oa.MotorType.DM8009,
            oa.MotorType.DM4340,
            oa.MotorType.DM4340,
            oa.MotorType.DM4310,
            oa.MotorType.DM4310,
            oa.MotorType.DM4310,
        ],
        [0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07],
        [0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17],
    )
    device.set_callback_mode_all(oa.CallbackMode.STATE)

    print("Enabling...")
    device.enable_all()
    time.sleep(0.1)
    device.recv_all()

    initial_q = [motor.get_position() for motor in device.get_motors()]
    hold_params = [
        oa.MITParam(kp, kd, q, 0.0, 0.0)
        for kp, kd, q in zip(
            [300, 300, 150, 150, 40, 40, 30],
            [2.5, 2.5, 2.5, 2.5, 0.8, 0.8, 0.8],
            initial_q,
        )
    ]
    device.mit_control_all(hold_params)
    device.recv_all()

    try:
        if args.side == "right":
            ideal, deltas = _run_right_sequence(device, mech_lim)
        else:
            ideal, deltas = _run_left_sequence(device, mech_lim)

        joint_order = [
            JointID.J1,
            JointID.J2,
            JointID.J3,
            JointID.J4,
            JointID.J5,
            JointID.J6,
            JointID.J7,
        ]
        ideal_delta_map = {
            joint: calc_delta_to_zero_pos_joint(
                initial_rad=initial_q[int(joint)],
                ideal_limit_rad=ideal[joint],
                delta_to_stop_rad=delta,
                joint_id=joint,
            )
            for joint, delta in zip(joint_order, deltas)
        }

        goal_abs = [
            initial_q[i] + ideal_delta_map.get(JointID(i), 0.0) for i in range(7)
        ]
        del goal_abs  # TODO: use for a precise-home refinement pass.

        device.disable_all()
        device.recv_all()
        device.set_zero_all()
        device.recv_all()
        print("wrote zero position to motors")

    except KeyboardInterrupt:
        print("\n[INFO] Ctrl+C pressed; stopping safely")
    finally:
        device.disable_all()
        print("[INFO] Motors disabled, exiting safely.")


if __name__ == "__main__":
    main()
